version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: health_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/health_db
      SECRET_KEY: your-super-secret-key-here
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      sh -c "uv run alembic upgrade head &&
             uv run uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload"

volumes:
  postgres_data:
