"""enhance models with new health sector fields

Revision ID: 2d34c4e3ebb5
Revises: 4546689d8c2d
Create Date: 2025-06-18 00:04:42.294464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d34c4e3ebb5'
down_revision = '4546689d8c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_type', sa.String(length=20), nullable=True))
    op.add_column('appointments', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('appointments', sa.Column('reminder_sent', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('follow_up_required', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('certifications', sa.Text(), nullable=True))
    op.add_column('doctors', sa.Column('languages_spoken', sa.Text(), nullable=True))
    op.add_column('doctors', sa.Column('ratings', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('profile_picture_url', sa.String(length=255), nullable=True))
    op.add_column('doctors', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('medical_records', sa.Column('record_type', sa.String(length=50), nullable=True))
    op.add_column('medical_records', sa.Column('attachments', sa.Text(), nullable=True))
    op.add_column('medical_records', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('medical_records', sa.Column('access_log', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('insurance_provider', sa.String(length=200), nullable=True))
    op.add_column('patients', sa.Column('insurance_policy_number', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('allergies', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('blood_type', sa.String(length=5), nullable=True))
    op.add_column('patients', sa.Column('preferred_language', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('lifestyle', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('family_history', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'family_history')
    op.drop_column('patients', 'lifestyle')
    op.drop_column('patients', 'preferred_language')
    op.drop_column('patients', 'blood_type')
    op.drop_column('patients', 'allergies')
    op.drop_column('patients', 'insurance_policy_number')
    op.drop_column('patients', 'insurance_provider')
    op.drop_column('medical_records', 'access_log')
    op.drop_column('medical_records', 'version')
    op.drop_column('medical_records', 'attachments')
    op.drop_column('medical_records', 'record_type')
    op.drop_column('doctors', 'department')
    op.drop_column('doctors', 'profile_picture_url')
    op.drop_column('doctors', 'ratings')
    op.drop_column('doctors', 'languages_spoken')
    op.drop_column('doctors', 'certifications')
    op.drop_column('appointments', 'follow_up_required')
    op.drop_column('appointments', 'reminder_sent')
    op.drop_column('appointments', 'location')
    op.drop_column('appointments', 'appointment_type')
    # ### end Alembic commands ###
