"""add new health sector feature models

Revision ID: a702016c224d
Revises: 2d34c4e3ebb5
Create Date: 2025-06-18 00:35:47.254464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a702016c224d'
down_revision = '2d34c4e3ebb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
